name: build go app 
on: 
  push:
    branches:
    #test push branch
    - 'release/v1.0'
    - '!release/v*-'
    - '!release/beta'
    - '!v*'
    - '!<branch>-*'
    paths-ignore:
    - '.gitignore'

jobs:
  test_rigger:
    runs-on: ubuntu-latest
    steps:
      - name: setup go environment
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'

      - name: checkout source
        uses: actions/checkout@v3

      - name: install go dependency
        uses: actions/go-dependency-submission@v1
        with:
          # GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner
          token: ${{ github.token.SHI_XU }}
          # optional, default is ${{ github.token }}
          # User provided map of max key/value pairs of metadata to include with the snapshot e.g. {"lastModified": "12-31-2022"}
          go-mod-path: go.mod
          # default is go.mod
          # Build target to detect build dependencies. If unspecified, will use "all", with will detect all dependencies used in all build targets (including tests and tools).
          go-build-target: all
          # default is all

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
