name: build go app 
on: 
  push:
    branches:
    #test for branch name release/v16.01
    - 'release/v[0-9]+\.[0-9]+'
    - '!release/v[0-9]+\.[0-9]+\-'
    - '!release/beta'
    - '!v[0-9]+\.[0-9]+'
    - '!feature-[0-9]+'
    paths-ignore:
    - '.gitignore'

jobs:
  test_rigger:
    # permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: setup go environment
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'

      - name: checkout source
        uses: actions/checkout@v3

      - name: install go dependency
        uses: actions/go-dependency-submission@v1
        with:
          go-mod-path: go.mod
          token: ${{ secrets.PAT }}
          go-build-target: all

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA 56 Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* ${{ secrets.MY_NAME }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* <${{ secrets.MY_NUS_EMAIL_ADDRESS }}|${{ secrets.MY_NUS_EMAIL_ADDRESS }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Metriculation:* ${{ secrets.MY_NUS_METRICULATION }} "
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* <${{ secrets.REPO_URL }}|${{ secrets.REPO_URL }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ secrets.RAILWAY_DEPLOY_URL }}|${{ secrets.RAILWAY_DEPLOY_URL }}>"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "go"
                    },
                    "value": "click_me_123",
                    "url": "${{ secrets.RAILWAY_DEPLOY_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Install Railway
        run: npm i -g @railway/cli

      # test for only one service on railway project 
      - name: Deploy to railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        