name: those lovely bears show how I feeling for this deploy
on: 
  push:
    branches:
    # test for last v16.02
    - 'release/v[0-9]+\.[0-9]+'
    - '!release/v[0-9]+\.[0-9]+\-'
    - '!release/beta'
    - '!v[0-9]+\.[0-9]+'
    - '!feature-[0-9]+'
    paths-ignore:
    - '.gitignore'

jobs:
  test_rigger:
    if: "!startswith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest
    
    steps:
      - name: first, setup go environment
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.17.0'

      - name: second, checkout source
        uses: actions/checkout@v3

      - name: third, install go dependency
        uses: actions/go-dependency-submission@v1
        with:
          go-mod-path: go.mod
          token: ${{ secrets.PAT }}
          go-build-target: all
      
      - name: then, deploy to railway
        uses: bervProject/railway-deploy@main
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          service: "${{ secrets.MY_SERVICE }}"

      - name: last but not least, let's send notification to slack
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA 56 Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* ${{ secrets.MY_NAME }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* ${{ secrets.MY_NUS_EMAIL_ADDRESS }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Metriculation:* ${{ secrets.MY_NUS_METRICULATION }} "
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* <${{ secrets.REPO_URL }}|${{ secrets.REPO_URL }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ secrets.RAILWAY_DEPLOY_URL }}|${{ secrets.RAILWAY_DEPLOY_URL }}>"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "emoji": true,
                      "text": "go"
                    },
                    "value": "click_me_123",
                    "url": "${{ secrets.RAILWAY_DEPLOY_URL }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

        